### ISSUE TITLE
Add more Material icons

### ISSUE THREAD

**Issue by QuadFlask** [konifar/android-material-design-icon-generator-plugin#13]
I found good Material icons from [https://github.com/Templarian/MaterialDesign](https://github.com/Templarian/MaterialDesign).
It looks good and many useful icons included.

**Comment by Akeru** [comment]
+1

**Comment by ahornerr** [comment]
Unfortunately the library isn't setup for SVG or .design files at the moment so this would be a difficult (see: time consuming) task.

**Comment by konifar** [comment]
As ahornerr said, this library is not supported .svg or .design files.
If someone provides .png files, I may be able to add new icons.

**Comment by ralphilius** [comment]
@konifar @ahornerr 
They have .svg file or do we need something else?
https://github.com/Templarian/MaterialDesign/tree/master/icons/svg
