### ISSUE TITLE
Cannot find resource dir

### ISSUE THREAD

**Issue by TakumaLee** [konifar/android-material-design-icon-generator-plugin#18]
Hello, I'm using the version 1.2, and now has the same problem.
I see the new UI about Res Directory, is it need to be changed?

**Comment by tigerss** [comment]
Hi, I think I had the same problem. I found that there is an option 'Res Directory' in the generator dialog where I specified the path to my res folder.

**Comment by konifar** [comment]
The new version 1.3 was released. Probably this bug was fixed. Please try it.
If it does not work, please tell me the details.
