### ISSUE TITLE
Support for transparency (for Navigation Drawer)

### ISSUE THREAD

**Issue by ChristopheVersieux** [konifar/android-material-design-icon-generator-plugin#24]
As explained in guidelines (link below) , Drawer icon should be: 54% #000000
Maybe I am wrong, but is seems that the current plugin doesn't allow such icons. Should we work with alpha in xml (which might not be a good idea regarding performances?)

http://www.google.com/design/spec/patterns/navigation-drawer.html#navigation-drawer-specs

**Comment by Frank1234** [comment]
Same thing here, for this lib to be helpful it needs to support transparency 54%.

**Comment by konifar** [comment]
@ChristopheVersieux @Frank1234 
The next version 1.3 will be released after few days.
New version supports transparency color. You can set 54% (8A~) transparency.

<img width="708" alt="material_icon_generator" src="https://cloud.githubusercontent.com/assets/1269214/8532120/f62536d2-2466-11e5-97e8-fc3fa83f9f3d.png">

**Comment by ChristopheVersieux** [comment]
Well done sir!

**Comment by ahornerr** [comment]
:+1:

**Comment by konifar** [comment]
@ChristopheVersieux @Frank1234 
New version was released. Please try it :)

**Comment by Frank1234** [comment]
Awesome, thanks!
