### ISSUE TITLE
Update to Material Design Icons 2.0

### ISSUE THREAD

**Issue by mars3142** [konifar/android-material-design-icon-generator-plugin#26]
I miss e.g. https://www.google.com/design/icons/#ic_power_settings_new

The changelog for 2.0 said: **More than 80 new icons**

**Comment by konifar** [comment]
@mars3142 Thanks for your good issue. I'll add new icons on next version 1.4 :)

**Comment by ohmp** [comment]
@mars3142 have find icon you mentioned.

**Comment by shiraji** [comment]
Isn't it better idea that adding https://github.com/google/material-design-icons as a submodule or subtree?

**Comment by benju69** [comment]
Hey there is new icons :) 96 icons for the 2.1 update
https://plus.google.com/u/0/+googledesign/posts/a5ePM9vzAVA

**Comment by vanniktech** [comment]
There's already a PR for this: #38

**Comment by konifar** [comment]
v1.4 was released. It contains latest material design icons!

**Comment by konifar** [comment]
<img width="708" alt="material_icon_generator" src="https://cloud.githubusercontent.com/assets/1269214/12214313/a98e159c-b6d2-11e5-98a4-f33d7fe4ec24.png">
