### ISSUE TITLE
Download link in the README.md could not be found

### ISSUE THREAD

**Issue by RahulSDeshpande** [konifar/android-material-design-icon-generator-plugin#28]
Seems, the link provided in the README.md is broken.
LINK > [https://github.com/konifar/android-material-design-icon-generator-plugin/raw/master/MaterialDesignIconGeneratorPlugin.jar]
Could you please update it.

**Comment by konifar** [comment]
Oh, sorry. I'll fix soon. Thank you for your issue.

**Comment by konifar** [comment]
@RahulSDeshpande I updated jar file. Could you please check it.

**Comment by RahulSDeshpande** [comment]
The link is perfect now !!

Thanks a lot @konifar :dancer:

Cheers !!

**Comment by konifar** [comment]
@RahulSDeshpande That's good! Thank you for your report.
