### ISSUE TITLE
Other Colors???

### ISSUE THREAD

**Issue by TurKurT656** [konifar/android-material-design-icon-generator-plugin#3]
can we have other custom colors on this plugin?

**Comment by konifar** [comment]
Thank you for your opinion! 
I use [material-design-icons](https://github.com/google/material-design-icons). So you cannot use colorful icons excepting that repository... Sorry.

But I planned to add other color icons like [ic_error_red_18dp](https://github.com/google/material-design-icons/blob/master/alert/drawable-hdpi/ic_error_red_18dp.png) or [ic_warning_amber_18dp](https://github.com/google/material-design-icons/blob/master/alert/drawable-hdpi/ic_warning_amber_18dp.png) :)
