### ISSUE TITLE
Looks like This is inside of Android Studio 1.4 now 

### ISSUE THREAD

**Issue by danielgomezrico** [konifar/android-material-design-icon-generator-plugin#32]
Check here: https://youtu.be/ssayKH0tudk?t=27m59s

**Comment by konifar** [comment]
Wow! But does this function not have incremental search?
For example, when I want to search 'star' icons, I can not search by the keyword.

**Comment by vanniktech** [comment]
The built in version is in my opinion really crappy. This plugin is still AFAIK the best solution out there.

**Comment by konifar** [comment]
@vanniktech Thanks so much!
