### ISSUE TITLE
do not have "ic_router_black" but google material design icon contain it

### ISSUE THREAD

**Issue by xmagicj** [konifar/android-material-design-icon-generator-plugin#36]
it's very useful plugin

but in version 1.3 
do not have "ic_router_black"
Google material design icons contain it

thank you~

**Comment by vanniktech** [comment]
Seems like the icons weren't updated. Also the new ones as described in #37

**Comment by konifar** [comment]
v1.4 was updated. It contains latest material design icons!

<img width="708" alt="material_icon_generator" src="https://cloud.githubusercontent.com/assets/1269214/12214324/f9c7f622-b6d2-11e5-95f7-9d06626b488b.png">

**Comment by xmagicj** [comment]
love you  me me da~
