### ISSUE TITLE
New Icons

### ISSUE THREAD

**Issue by kidouchi** [konifar/android-material-design-icon-generator-plugin#37]
There are a lot of new icons available on Google's material icon website. Possibly update?

**Comment by vanniktech** [comment]
+1

**Comment by andyb129** [comment]
I've just added these and submitted a pull request :+1:

**Comment by goceancx** [comment]
+1

**Comment by androideveloper** [comment]
+1

**Comment by kaszuster** [comment]
+1

**Comment by konifar** [comment]
v1.4 was released. It contains latest material design icons!

<img width="708" alt="material_icon_generator" src="https://cloud.githubusercontent.com/assets/1269214/12214318/d296b250-b6d2-11e5-811b-80a06bd21c10.png">

**Comment by ravithoria** [comment]
missing **outlined** icon
