### ISSUE TITLE
Resource dir can not be found

### ISSUE THREAD

**Issue by aristide** [konifar/android-material-design-icon-generator-plugin#4]
I'm trying to generate icons. But i'm getting the error : "Resource dir can not be found" 
help !!

**Comment by aheusingfeld** [comment]
same here

**Comment by ashughes** [comment]
I'm getting this same issue as well.

**Comment by something15525** [comment]
Me as well! Where do you right click to generate? which folder?

**Comment by MyWay** [comment]
Same here.

**Comment by konifar** [comment]
@aristide @aheusingfeld @ashughes @something15525 @MyWay 
Thank you for your report! This plugin could not change resource dir. But @amc6 sent great pull request.
https://github.com/konifar/android-material-design-icon-generator-plugin/pull/8

I already merge this fix. After release new version v1.1, this issue probably solved.

**Comment by tajchert** [comment]
Thanks it works perfectly now. I think you can close this issue.

**Comment by konifar** [comment]
@tajchert Thank you for your comment. New version v1.1 was released, so I close this issue.

**Comment by aldefy** [comment]
for me it still exists in v 1.1 , how to set resource directory ?!

**Comment by TakumaMochizuki** [comment]
Hello, I'm using the version 1.2, and now has the same problem, and now I see the new UI about Res Directory, is it need to changed?
