### ISSUE TITLE
Color issue with generating in 24dp and 48dp

### ISSUE THREAD

**Issue by dsdebastiani** [konifar/android-material-design-icon-generator-plugin#40]
Some icons with dimen `24dp` and `48dp` have an issue. The image is total filled with color in resolutions bigger than `hdpi`.

I didn't try with all icons. But the icon wich I need have the problem: `ic_add` with white color, but the same problem occurs with any color. See images attached.

![material icon generator_001](https://cloud.githubusercontent.com/assets/5443979/12392259/ca818032-bdd4-11e5-9e61-3701bba5cfe3.png)
![material icon generator_002](https://cloud.githubusercontent.com/assets/5443979/12392282/f9e30350-bdd4-11e5-9d37-db82a14665f4.png)

**Comment by shimika** [comment]
It something wrong to me also.

**Comment by ferbeb** [comment]
Same here, trying to add av/ic_playlist_add (18dp), running Android Studio on Ubuntu. Can also confirm ic_add is not working for high resolutions at 18dp.

**Comment by igorsousa-b** [comment]
Same happens to me, running Android Studio on OS X.

**Comment by ShkurtiA** [comment]
same here

**Comment by efemoney** [comment]
Same thing with ic_add.

**Comment by cat9** [comment]
@dsdebastiani @shimika @ferbeb @igorsousa-b  @ShkurtiA 
hi，guys
i fixed it on my fork，and something differently also.hope it helps.

**Comment by pratamawijaya** [comment]
+1
