### ISSUE TITLE
Could you please tell me the background image plugin name?

### ISSUE THREAD

**Issue by kuoruan** [konifar/android-material-design-icon-generator-plugin#60]
I see your editor has a background image, I very like it. Can you tell me the plugin name? Thinks !

PS: If this issue trouble you, just close it.

**Comment by konifar** [comment]
@kuoruan Hi, this appearance theme is default option.
You can change theme in Preference > Appearance > UI Options > Theme

<img width="1037" alt="preferences" src="https://cloud.githubusercontent.com/assets/1269214/15452189/196a440a-2021-11e6-9489-7dcd03cfc493.png">

**Comment by kuoruan** [comment]
Well , I mean is your editor has a background image.
![capture](https://raw.githubusercontent.com/konifar/android-material-design-icon-generator-plugin/master/docs/capture.gif)

The girl in this gif ( Koto no ha no niwa ? ). I want to know what is the plugin.

**Comment by konifar** [comment]
Oh, sorry! Yes, This woman is Ms. Yukino in Koto-no-ha-no-niwa 😃 
This plugin is Sexy Editor.
https://plugins.jetbrains.com/plugin/1833

**Comment by kuoruan** [comment]
Thank you very much.
