### ISSUE TITLE
Add night qualifier support

### ISSUE THREAD

**Issue by vanniktech** [konifar/android-material-design-icon-generator-plugin#61]
Could be a simple checkbox and then it'd move the icons to:
- drawable-night-ldpi
- drawable-night-mdpi
- drawable-night-xhdpi
- drawable-night-xxhdpi
- drawable-night-xxxhdpi

**Comment by keluokeda** [comment]
yes ,i have some problem,need night drawable

**Comment by vanniktech** [comment]
@konifar is this something you'd like to offer?

**Comment by vanniktech** [comment]
Gentle bump.

**Comment by vanniktech** [comment]
Stopped using this plugin.
