### ISSUE TITLE
Get rid of are you sure you want to generate this icon

### ISSUE THREAD

**Issue by vanniktech** [konifar/android-material-design-icon-generator-plugin#66]
I don't know how many are a fan of this dialog but it's useless in my opinion. Just generate the icon when pressing ok

**Comment by konifar** [comment]
Good suggestion! Thanks!
I'll remove the dialog on next release 😉

**Comment by vanniktech** [comment]
@konifar are you open for a PR on this one?

**Comment by konifar** [comment]
Sorry, I haven't done this yet 🙇

**Comment by vanniktech** [comment]
Gentle push.

**Comment by WillieCubed** [comment]
Ready yet? 😄
